branches:
  only:
    - master

version: 0.1.{build}-ci
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

os: Visual Studio 2015
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  nuget restore "src/YAXL.Redux.sln"

configuration: Release
platform: Any CPU

build:
  parallel: true
  project: src/YAXL.Redux/YAXL.Redux.csproj
  verbosity: minimal
  
after_build:
  - ps: nuget pack src/YAXL.Redux/YAXL.Redux.csproj -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\YAXL.Redux.*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: LT8bWnUXsN/QwIft5V3jlpmBFz9k5TXXceJ8j42eHYOD79VJ9jaf+qlxq2vy173K
