branches:
  only:
    - master
    
environment:
  COVERALLS_REPO_TOKEN:  
       secure: JzwU2ypXVCytUn2T7TMFVDepjeoxGvy847LoRM5e25YJRDDGjGpV4VR2ydB7TBWE

image: Visual Studio 2017

version: 0.5.{build}-ci

build_script:
  - cmd: msbuild src\YAXL.Redux\YAXL.Redux.csproj /t:restore
  - cmd: msbuild src\YAXL.Redux\YAXL.Redux.csproj /t:pack /p:Configuration=Release /p:Version="%APPVEYOR_BUILD_VERSION%"
  - cmd: msbuild src\YAXL.Redux.XamarinForms\YAXL.Redux.XamarinForms.csproj /t:restore
  - cmd: msbuild src\YAXL.Redux.XamarinForms\YAXL.Redux.XamarinForms.csproj /t:pack /p:Configuration=Release /p:Version="%APPVEYOR_BUILD_VERSION%"

artifacts:
  - path: '**\YAXL.Redux.*.nupkg'
