branches:
  only:
    - master

image: Visual Studio 2017

version: 0.3.{build}-ci

build_script:
  - cmd: msbuild src\YAXL.Redux\YAXL.Redux.csproj /t:restore
  - cmd: msbuild src\YAXL.Redux\YAXL.Redux.csproj /t:pack /p:Configuration=Release

artifacts:
  - path: '**\YAXL.Redux.*.nupkg'